### ISSUE TITLE
Error in step 9

### ISSUE THREAD

**Issue by aadelabk** [asphub/ng5AppEx#2]
In step 9 the create.component.ts is to edited as following

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-create',
  templateUrl: './create.component.html',
  styleUrls: ['./create.component.css']
})
export class CreateComponent implements OnInit {

  title = 'Add Coin';
  constructor() { }

  ngOnInit() {
  }

}

here if you are using SCSS as your styling format then you have to change line no 6 to
         styleUrls: ['./create.component.scss']

**Comment by aadelabk** [comment]
chnage the create.component file to .scss file format

**Comment by asphub** [comment]
fixed
